version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      root-development:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /mobile/capacitor
    schedule:
      interval: weekly
    groups:
      capacitor-mobile:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
